# Generated by Django 3.0.3 on 2020-11-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konsumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('saldo', models.IntegerField()),
                ('kontak', models.CharField(max_length=200)),
            ],
        ),
    ]
